### ISSUE TITLE
zod-openapi v3.1.0 compatibility

### ISSUE THREAD

**Issue by cameralis** [samchungy/fastify-zod-openapi#166]
Hey there, thank you for this amazing library!

I've seen you just updated the zod-openapi package which my package manager pulled immediately, but unfortunately the signature of the createParamOrRef no longer matches, since you added the CreateDocumentOptions argument. Luckily I was able to downgrade it and get it working successfully!

**Comment by samchungy** [comment]
Ah bugger, I'll patch it out with zod-openapi. Apologies for that

**Comment by samchungy** [comment]
Should be resolved in 3.1.1. Thank you once again!
