### ISSUE TITLE
Fastify's swagger crash when using @fastify/swagger 9.2.0 with zod-openapi auto registering schema

### ISSUE THREAD

**Issue by mottet** [samchungy/fastify-zod-openapi#172]
## What is the bug

Fastify's swagger does not load when using zod-openapi [auto registering schema](https://www.npmjs.com/package/zod-openapi#creating-components) with @fastify/swagger@9.2.0

## How to reproduce the bug

I have create a repository that repoduce this issue: https://github.com/mottet/bug-fastify-zod-openapi

First start the fastify server

``` bash
npm install
npm serve
```

Then try to open the swagger page: <http://127.0.0.1:5000/documentation>

The error "Failed to load API definition." should appear.

## What causes this bug

Since @fastify/swagger version 9.2.0 that contains this PR <https://github.com/fastify/fastify-swagger/pull/826>, when a response with no description contains a reference, it will try to get the description from the reference.

But this happen AFTER fastify-zod-openapi had add the ref in the response, but BEFORE fastify-zod-openapi created the actual component. So fastify/swagger try [at this line](https://github.com/fastify/fastify-swagger/blob/master/lib/util/resolve-schema-reference.js#L13) to get a defnition on a component that does not exist yet and throw the error:

```
Exception has occurred: TypeError: Cannot read properties of undefined (reading 'schemas')
``` 

This description fallback happens in [this function call](https://github.com/fastify/fastify-swagger/blob/master/lib/spec/openapi/index.js#L52) that is between the 2 transformation steps of fastify-zod-openapi [here](https://github.com/fastify/fastify-swagger/blob/master/lib/spec/openapi/index.js#L31) and [here](https://github.com/fastify/fastify-swagger/blob/master/lib/spec/openapi/index.js#L73)

## Workaround

Downgrade @fastify/swagger from 9.2.0 to 9.1.0

## How to fix it

The fix can be easy by simply change in https://github.com/fastify/fastify-swagger/blob/master/lib/util/resolve-schema-reference.js

``` javascript
return resolvedReference.definitions[schemaId]
```

to this

``` javascript
return resolvedReference.definitions?.[schemaId]
```

I'm contacting you even if this issue seems to be more on the fastify/swagger side, because it is an edge case that is "setup" by zod-openapi and fastify-zod-openapi and affects you directly.

**Comment by samchungy** [comment]
We potentially might be able to write the components in the fly too 🤔

**Comment by mottet** [comment]
I think I will raise a PR on fastify/swagger side with the fix I explained on https://github.com/fastify/fastify-swagger/blob/master/lib/util/resolve-schema-reference.js as it allow edge cases like ours to not crash. It will return undefined in our case but it's already a possible return of the function, so it doesn't impect them.

**Comment by mottet** [comment]
Looks like I missed this PR https://github.com/fastify/fastify-swagger/pull/830 where another developer has the exacte same issue and already proposed the same fix as me haha
Linking this issue to the PR so they have more details.

**Comment by samchungy** [comment]
We might be able to fix it on our side actually

**Comment by samchungy** [comment]
I may have an alternate workaround but I'll need to experiment this weekend

**Comment by samchungy** [comment]
Nevermind, looks like the component resolution within fastify-swagger is completely broken.. That fix will have to do for now..

**Comment by samchungy** [comment]
Just pending the release of the above PR ^ to fix our issue, then I've got a big update upcoming 😅

**Comment by mottet** [comment]
Super! Thank you for your work 😄

**Comment by samchungy** [comment]
Peer dependency version has been pinned in 3.0.0. I'll keep this open to keep track of when @fastify/swagger releases
