### ISSUE TITLE
Is it possible to type a context?

### ISSUE THREAD

**Issue by thelinuxlich** [samchungy/fastify-zod-openapi#54]
I have some prehandlers enriching the request context(like auth data), is it possible to achieve typesafety in the route handlers receiving the context data?

**Comment by samchungy** [comment]
Could you post an example? Unfortunately I don't actively use fastify right now so I'm not quite sure what you mean

**Comment by thelinuxlich** [comment]
I will give you an example of this in another framework: https://www.zodios.org/docs/server/express-context

**Comment by samchungy** [comment]
Hey sorry, I forgot to come back to this, but this might be more of a Fastify question, as we just lean into their type provider system
