### ISSUE TITLE
Unable to use the project in an ESM context

### ISSUE THREAD

**Issue by chuck-flowers** [samchungy/fastify-zod-openapi#88]
Hello, I'm very interested in attempting to make use of this in an existing project I have. The issue I'm running into, is that I'm unable to successfully use the package when I import it into one of the modules of my application due to a ESM/CJS incompatibility.

If I import the package in the following way:
```typescript
import { } from 'fastify-zod-openapi';
```

The CJS module gets imported and when the `fastify/@swagger` transformers run, the `instanceof` checks against `zod` types fail because I'm using the ESM version of `zod` whereas your CJS module is using the CJS version of `zod`.

I attempted to address this problem by importing it in the following way instead since you seemed to have a ESM version of the package as well:

```typescript
import { } from 'fastify-zod-openapi/lib-es2015'
```

When I did this though, I got an error regarding missing type definitions. I hacked some type definitions together on my side, but then when I ran the code to test it, there were import failures. I launched `node` without any arguments and executed the following statement in the REPL:

```javascript
await import('fastify-zod-openapi/lib-es2015/index.js')
```

After running that command, I received the following output
```
(node:30672) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/cflowers/source/repos/apps/uspack-dot/node_modules/.pnpm/fastify-zod-openapi@1.0.2_fastify@4.26.1_zod-openapi@2.13.0_zod@3.22.4/node_modules/fastify-zod-openapi/lib-es2015/index.js:1
export * from './plugin';
^^^^^^
```

It seems the remedy to the problems I'm having would be to:

1. Emit type definitions for `fastify-zod-openapi/lib-es2015/index.js`
2. Update the package to under stand that `fastify-zod-openapi/lib-es2015/index.js` is an ESM.

If there is another existing solution to using this package in an ESM application that I've overlooked, please let me know.

**Comment by samchungy** [comment]
Hey there thanks for raising!

This looks similar to https://github.com/samchungy/zod-openapi/pull/208. I'll take a look when I have a bit of time 🙂

**Comment by samchungy** [comment]
Hey! Please give 1.1.0 a shot and let me know :)
