### ISSUE TITLE
Operation description and summary

### ISSUE THREAD

**Issue by xmonkee** [samchungy/fastify-zod-openapi#98]
First of all, thank you for a wonderful library. Solves the exact issue I was having gluing together a bunch of disparate solutions.

Is there a way to add a description and summary to an endpoint?

**Comment by samchungy** [comment]
Hey there, thanks for the kind words!

https://github.com/samchungy/fastify-zod-openapi/blob/55cf90a24847025da551e108c473aa69c94f790d/examples/openapi.ts#L78

You can define a `description` here on the same level as `content`, but it looks like `fastify-swagger` swallows up the `summary` field. You'd need to raise a PR [here](https://github.com/fastify/fastify-swagger/blob/352f7d6c235445731e9843c1f83f313d5320992e/lib/spec/swagger/utils.js#L238)

**Comment by xmonkee** [comment]
Thanks. But this is a description of the response, not of the operation itself, yeah?

**Comment by samchungy** [comment]
Ah I see, my mistake, the operation.... 🙈

You should be able to declare them under the `schema` section.

https://github.com/samchungy/fastify-zod-openapi/blob/55cf90a24847025da551e108c473aa69c94f790d/examples/openapi.ts#L51

eg.

```
  app.withTypeProvider<FastifyZodOpenApiTypeProvider>().route({
    method: 'POST',
    url: '/:jobId',
    schema: {
      description: 'hello',
      summary: 'world',
      params: z.object({
        foo: z.string().openapi({
          description: 'path parameter example',
          example: 'bar',
        }),
      }),
      response: {
        200: z.object({
          jobId: JobIdSchema,
        }),
        201: {
          description: 'poo',
          summary: 'bar',
          content: {
            'application/json': {
              example: { jobId: '123' },
              schema: z.object({
                jobId: z.string().openapi({
                  description: 'Job ID',
                  example: '60002023',
                }),
              }),
            },
          },
        },
      },
    } satisfies FastifyZodOpenApiSchema,
    handler: async (_req, res) =>
      res.send({
        jobId: '60002023',
      }),
  });
```

**Comment by xmonkee** [comment]
Wonderful, thank you! Sending a coffee your way
